- name: Install Filebeat
  hosts: "nginx"
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install gnupg and apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy GPG key file
      copy:
        src: /home/kali/diplom/ansible/files/GPG-KEY-elasticsearch
        dest: /tmp/GPG-KEY-elasticsearch

    - name: Get Filebeat 8.10.3
      ansible.builtin.get_url:
        url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.10.3-amd64.deb
        dest: /tmp/

    - name: Install Filebeat
      apt:
        deb: /tmp/filebeat-8.10.3-amd64.deb

    - name: Copy config file for Filebeat
      copy:
        src: /home/kali/diplom/ansible/files/filebeat.yml
        dest: /etc/filebeat
        mode: '0600'
        owner: root
        group: root

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Reload systemd daemon and start Filebeat service
      systemd:
        daemon_reload: true
        name: filebeat.service
        state: started