---
- name: Install Kibana
  hosts: kibana
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install gnupg and apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy GPG key file
      copy:
        src: /home/kali/diplom/ansible/files/GPG-KEY-elasticsearch
        dest: /tmp/GPG-KEY-elasticsearch

    - name: Get Kibana 8.10.3
      ansible.builtin.get_url:
        url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/k/kibana/kibana-8.10.3-amd64.deb
        dest: /tmp/

    - name: Install Kibana
      apt:
        deb: /tmp/kibana-8.10.3-amd64.deb

    - name: Copy config file for Kibana
      ansible.builtin.copy:
        src: /home/kali/diplom/ansible/files/kibana.yml
        dest: /etc/kibana/kibana.yml
        mode: '0644'
        owner: root
        group: root

    - name: Restart Kibana
      service:
        name: kibana
        state: restarted   

    - name: Enable Kibana service
      ansible.builtin.service:
        name: kibana
        enabled: yes